// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppAside: typeof import('./src/components/AppAside.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppLanguage: typeof import('./src/components/AppLanguage.vue')['default']
    AppTheme: typeof import('./src/components/AppTheme.vue')['default']
    copy: typeof import('./src/components/OEchart copy.vue')['default']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    OBar: typeof import('./src/components/OBar.vue')['default']
    OEchart: typeof import('./src/components/OEchart.vue')['default']
    OEchartBar: typeof import('./src/components/OEchartBar.vue')['default']
    OEchartFunnel: typeof import('./src/components/OEchartFunnel.vue')['default']
    OEchartGauge: typeof import('./src/components/OEchartGauge.vue')['default']
    OEchartLine: typeof import('./src/components/OEchartLine.vue')['default']
    OEchartPie: typeof import('./src/components/OEchartPie.vue')['default']
    OEchartPieOfTable: typeof import('./src/components/OEchartPieOfTable.vue')['default']
    OEchartPieTable: typeof import('./src/components/OEchartPieTable.vue')['default']
    OEchartText: typeof import('./src/components/OEchartText.vue')['default']
    OFormRadio: typeof import('./src/components/OFormRadio.vue')['default']
    OLabel: typeof import('./src/components/OLabel.vue')['default']
    OProTable: typeof import('./src/components/OProTable.vue')['default']
    OTableDiag: typeof import('./src/components/OTableDiag.vue')['default']
    OTableDialog: typeof import('./src/components/OTableDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
